// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa6SGI8yCRt06dauV7rI8F9ngWonCESdk',
    appId: '1:1024602090224:web:659c95d6d8b63528137035',
    messagingSenderId: '1024602090224',
    projectId: 'vendbmr',
    authDomain: 'vendbmr.firebaseapp.com',
    databaseURL: 'https://vendbmr-default-rtdb.firebaseio.com',
    storageBucket: 'vendbmr.appspot.com',
    measurementId: 'G-Q0N4122K4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7yfmD0Ho0c2qq3q1skTPytGWK6IUA-Jc',
    appId: '1:1024602090224:android:34979b3dc1b341bd137035',
    messagingSenderId: '1024602090224',
    projectId: 'vendbmr',
    databaseURL: 'https://vendbmr-default-rtdb.firebaseio.com',
    storageBucket: 'vendbmr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIxFlhSK5Ins-XRUzPZjCwk9P20jEgzdw',
    appId: '1:1024602090224:ios:14308d01c405e4df137035',
    messagingSenderId: '1024602090224',
    projectId: 'vendbmr',
    databaseURL: 'https://vendbmr-default-rtdb.firebaseio.com',
    storageBucket: 'vendbmr.appspot.com',
    iosClientId: '1024602090224-tf24tstdi4cjofb6onn0182sv9uj82gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.payDrink',
  );
}
